/*
 * MainAboutPanel.java
 *
 * Created on 23 Mar 2006, 19:40
 *
 * AsItHappens - real-time network monitor
 * Copyright (C) 2006  Mark Abrahams
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

package nz.co.abrahams.asithappens.mainui;

/**
 * The panel showing application information.
 *
 * @author  mark
 */
public class MainAboutPanel extends javax.swing.JPanel {
    
    /** Creates new form MainAboutPanel */
    public MainAboutPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titleLabel.setText("AsItHappens 0.60");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        descriptionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descriptionLabel.setText("Real-time network performance monitor");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        copyrightLabel.setText("(c) 2006-2012 Mark Abrahams");
        add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon("images/logo.png"));
        add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 50));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
