/*
 * DatabaseCreateDialog.java
 *
 * Created on 7 April 2006, 00:06
 */

package nz.co.abrahams.asithappens.core;

import nz.co.abrahams.asithappens.uiutil.ErrorHandler;

/**
 *
 * @author  mark
 */
public class DBCreateDialog extends javax.swing.JDialog {
    
    /** Creates new form DatabaseCreateDialog */
    public DBCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionTopLabel = new javax.swing.JLabel();
        instructionBottomLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database needs creating");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionTopLabel.setText("You can create the AsItHappens database by entering");
        getContentPane().add(instructionTopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        instructionBottomLabel.setText("the MySQL administrator user name and password");
        getContentPane().add(instructionBottomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        usernameField.setText("root");
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 250, -1));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        //DatabaseCreate dbCreate;
        
        try {
            DBCreate.create(usernameField.getText(), new String(passwordField.getPassword()));
        } catch (Exception e) {
            ErrorHandler.modalError(this, "Cannot create database", "Please check database connectivity", e);
        } finally {
            dispose();
        }
    }//GEN-LAST:event_createButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel instructionBottomLabel;
    private javax.swing.JLabel instructionTopLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
    
}
